# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tuf.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttuf.proto\x12\x03tuf\"T\n\x08\x45nvelope\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x13\n\x0bpayloadType\x18\x02 \x01(\t\x12\"\n\nsignatures\x18\x03 \x03(\x0b\x32\x0e.tuf.Signature\"\'\n\tSignature\x12\x0b\n\x03sig\x18\x01 \x01(\x0c\x12\r\n\x05keyid\x18\x02 \x01(\t\"\x1a\n\x08KeyValue\x12\x0e\n\x06public\x18\x01 \x01(\t\"E\n\x03Key\x12\x0f\n\x07keytype\x18\x01 \x01(\t\x12\x0e\n\x06scheme\x18\x02 \x01(\t\x12\x1d\n\x06keyval\x18\x03 \x01(\x0b\x32\r.tuf.KeyValue\")\n\x04Role\x12\x0e\n\x06keyids\x18\x01 \x03(\t\x12\x11\n\tthreshold\x18\x02 \x01(\x04\"\x9f\x02\n\x08RootRole\x12\x14\n\x0cspec_version\x18\x01 \x01(\t\x12\x1b\n\x13\x63onsistent_snapshot\x18\x02 \x01(\x08\x12\x0f\n\x07\x65xpires\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\x04\x12%\n\x04keys\x18\x05 \x03(\x0b\x32\x17.tuf.RootRole.KeysEntry\x12\'\n\x05roles\x18\x06 \x03(\x0b\x32\x18.tuf.RootRole.RolesEntry\x1a\x35\n\tKeysEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x17\n\x05value\x18\x02 \x01(\x0b\x32\x08.tuf.Key:\x02\x38\x01\x1a\x37\n\nRolesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.tuf.Role:\x02\x38\x01\"\x85\x01\n\x08Snapshot\x12\x0f\n\x07version\x18\x01 \x01(\x04\x12\x0e\n\x06length\x18\x02 \x01(\x04\x12)\n\x06hashes\x18\x03 \x03(\x0b\x32\x19.tuf.Snapshot.HashesEntry\x1a-\n\x0bHashesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xad\x01\n\x0cSnapshotRole\x12\x14\n\x0cspec_version\x18\x01 \x01(\t\x12\x0f\n\x07\x65xpires\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\x04\x12)\n\x04meta\x18\x05 \x03(\x0b\x32\x1b.tuf.SnapshotRole.MetaEntry\x1a:\n\tMetaEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1c\n\x05value\x18\x02 \x01(\x0b\x32\r.tuf.Snapshot:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tuf_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROOTROLE_KEYSENTRY._options = None
  _ROOTROLE_KEYSENTRY._serialized_options = b'8\001'
  _ROOTROLE_ROLESENTRY._options = None
  _ROOTROLE_ROLESENTRY._serialized_options = b'8\001'
  _SNAPSHOT_HASHESENTRY._options = None
  _SNAPSHOT_HASHESENTRY._serialized_options = b'8\001'
  _SNAPSHOTROLE_METAENTRY._options = None
  _SNAPSHOTROLE_METAENTRY._serialized_options = b'8\001'
  _ENVELOPE._serialized_start=18
  _ENVELOPE._serialized_end=102
  _SIGNATURE._serialized_start=104
  _SIGNATURE._serialized_end=143
  _KEYVALUE._serialized_start=145
  _KEYVALUE._serialized_end=171
  _KEY._serialized_start=173
  _KEY._serialized_end=242
  _ROLE._serialized_start=244
  _ROLE._serialized_end=285
  _ROOTROLE._serialized_start=288
  _ROOTROLE._serialized_end=575
  _ROOTROLE_KEYSENTRY._serialized_start=465
  _ROOTROLE_KEYSENTRY._serialized_end=518
  _ROOTROLE_ROLESENTRY._serialized_start=520
  _ROOTROLE_ROLESENTRY._serialized_end=575
  _SNAPSHOT._serialized_start=578
  _SNAPSHOT._serialized_end=711
  _SNAPSHOT_HASHESENTRY._serialized_start=666
  _SNAPSHOT_HASHESENTRY._serialized_end=711
  _SNAPSHOTROLE._serialized_start=714
  _SNAPSHOTROLE._serialized_end=887
  _SNAPSHOTROLE_METAENTRY._serialized_start=829
  _SNAPSHOTROLE_METAENTRY._serialized_end=887
# @@protoc_insertion_point(module_scope)
